### ISSUE TITLE
Add build of kubernetes-crds and message-transport

### ISSUE THREAD

**Issue by ericbottard** [projectriff/ci#47]
Although they don't produce deliverables _per se_, those two projects should be built, to make sure they compile correctly and are up to date.

**Comment by jldec** [comment]
We had a similar problem with the function-proto repo - the java-function-invoker currently depends on a jar built from function-proto.

**Comment by ericbottard** [comment]
The situation with these two projects is not as problematic, as they are vendored into dependents anyway. It's more of a way to make sure that they compile upfront

**Comment by ericbottard** [comment]
Closing, as with monorepo these two libs are now directly built (they're in GOPATH) so there are less chances of breaking them and discovering damage later
