### ISSUE TITLE
FATS should use pre-built sample images

### ISSUE THREAD

**Issue by jchesterpivotal** [projectriff/ci#50]
Currently, `riff build` works with a local docker daemon to layer function code on top of a generic invoker container. This works well for local development environments, but causes great unhappiness in CI.

Instead, the Dockerfile should be generated and built separately from the system test.

This issue represents a blocker for projectriff/riff#258.

**Comment by jchesterpivotal** [comment]
I'm calling this done, since it caught up with the CLI change.

**Comment by jchesterpivotal** [comment]
Sike, still not covering Python or Java.

**Comment by jchesterpivotal** [comment]
Blocking on #52.

**Comment by jldec** [comment]
fixed with move to travis CI
